import React from 'react'
import Title from "../../../../../components/Title";
import Image from "../../../../../components/Image";
import Paragraph from "../../../../../components/Paragraph";

function Cerita() {
  return (
    <div className="flex flex-col  p-4 items-center bg-cyan-50 gap-3 text-neutral-900 ">
      <div className="flex flex-col  text-justify p-2 sm:px-16 md:px-28 lg:px-32 sm:py-10 bg-champagne_pink">
        <div className="flex flex-col items-center">
          <Title text="La Sallomo" />
          <Image src="/images/lasallomo.webp" alt="La Sallomo" />
        </div>
        {/* Paragraf mulai */}
        <Paragraph par="Pada suatu ketika, terbetiklah berita bahwa Addatuang Sidenreng akan mengadakan suatu pesta perkawinan. Berita saat dan acara-acara pesta tersebut telah tersiar kemana-mana, juga telah didengar oleh Raja Bone, bahwa Addatuang Sidenreng akan melaksanakan suatu pesta perkawinan. Rupanya ada kalangan tertentu di Bone yang hendak menggagalkan dan mencari muslihat untuk mengalahkan Sidenreng. Demikianlah suatu ketika telah diperintahkan pesuruh terpercaya dari Raja Bone (pakke) untuk mengantarkan sesuatu kepada Raja Sidenreng." />
        <Paragraph par="(Gelar pakke adalah seorang pesuruh Raja yang di perintahkan membawa seekor burung gereja). Lalu pesuruh itu membawa burung gereja menghadap Raja Sidenreng katanya “Konon kabarnya Addatuang Sidenreng akan mengadakan suatu pesta perkawinan, oleh karena itu Raja Bone telah memerintahkan hamba membawa lauk pauk guna makanan pada pesta perkawinail itu, maksudnya untuk dimakan pada hari itu juga, akan tetapi ji.kalau lauknya yang seekor itu ditambah dengan lauk pauk lain, maka ia akan menyerang Sidenreng. Raja Bone minta jadi makanan hanya burung yang seekor itu”. Dengan permintaan itu semua anggota Persekutuan Tujuh daerah Massenrengpulu menjadi susah, karena menurut mereka, sehari semalam telah disembelih tujuh ekor kerbau, juga belum cukup, apalagi dengan seekor burung gereja yang kecil itu saja, sedang dimakan seorang pun tak cukup. Kebetulan pada waktu itu ada seorang yang bernama La Sallomo (barangkali itulah yang kita kenal sekarang dengan gelar Nene' Mallomo)." />
        <Paragraph par="Orang yang bernama La Sallomo itu adalah orang yang selalu didatangi ilham, artinya mengetahui sesuatu tanpa dipelajari karena memang mendapat hidayah dari Dewata untuk menjawab segala tantangan lawan, katakanlah bahwa orang ini adalah cendekiawan orang Sidenreng. Lalu disuruh panggil La Sallomo oleh Raja dan katanya " />
        <Paragraph par="“Apa yang seharusnya yang kita perbuat kalau keadaan begini, Sallomo”, yaitu seekor burung gereja kecil menyebabkan kita akan diperangi, jikalau kita tidak mencukupkan sebagai makanan pada waktu hari perkawinan dilangsungkan." />
        <Paragraph par="“Dimanakah pesuruh itu sekarang Puang?” tanya La Sallomo. “Ada di pekarangan” sambung Raja. “Dapatkah ia menunggu saya ingin bercakap-cakap dengan mereka”, tanya La Sallomo memutuskan. " />
        <Paragraph par="Lalu disuruh panggil pesuruh kepercayaan Raja Bone untuk berembuk dengan La Sallomo. Lalu pergilah mengambil sebatang jarum yang amat kecil dan diserahkan kepada pesuruh itu, katanya " />
        <Paragraph par="“Lagi tujuh hari dengan hari ini upacara pesta perkawinan Addatuang akan dilangsungkan. Akan tetapi Addatuang Sidenreng hendak meminta kepada Tuanku Raja Bone agar dibuatkan alat penyembelih burung gereja itu berupa sebuah kapak, dengan pisau atau parang, masing-masing sebuah dibuat dari jarum ini, maksudnya kapak itu untuk dipakai memotong-motong,tulang-tulang, dengan parang atau pisau hendak di pakai mencencang dan mengiris-iris dagingnya burung gereja itu dan kalau tidak di an tar-. kan pada kami dalam tempo tiga hari lagi, maka Addatuang akan melangsungkan upacara itu”. " />
        <Paragraph par="Akan tetapi sampai pada hari yang. ditentukan tak ada seorang pun pesuruh yang datang, lalu dilangsungkanlah upacara perkawinan, karena memang orang Bone tidak dapat membuat alat-alat itu. Demikianlah jawaban kiriman seekor burung gereja kecil dari cendekiawan La Sallomo. Beberapa lama setelah pesta perkawinan Addatuang Sidenreng telah usai, datang lagi pesuruh Bone ke Sidenreng untuk mencari ayam empat puluh ekor yang sama bulunya dan sama bunyinya, maka mulai lagi orang Sidenreng susah, karena menurut pesuruh apabila barang yang di minta Raja Bone pada orang Sidenreng itu tidak ada, maka raja Bone akan memerangi Sidenreng, karena mereka berani, sebab banyak lasykarnya. " />
        <Paragraph par="Lalu orang mencoba mengumpulkan ayam putih yang sama bulunya akan tetapi tidak sama lagi bunyinya, maka makin susahlah orang Sidenreng. Ketika itu dipanggil lagi La Sallomo oleh Addatuang katanya. " />
        <Paragraph par="Adalagi perintah Raja Bone “Bagaimana perintah itu puang?” tanya La Sallomo. " />
        <Paragraph par="“Begini, kita disuruh lagi mencarikan·ayam empat puluh ekor yang. sama bulu dan sama bunyi, di mana kita dapat peroleh, benar-benar kita akan mati karena pasti kita akan diserang” kata Addatuang menjelaskan. " />
        <Paragraph par="“Jikalau demikian itu saja perintahnya, soal mudah Puang” jawab La Sallomo. “Kalau begitu saya serahkan saja bagaimana pikiranmu, karena pesuruh itu sudah ada menunggu”, sambung raja memutuskan. " />
        <Paragraph par="Lalu diperintahkan orang mencari 40 ekor anak ayam, tanpa induk untuk dibawa pesuruh itu ke Bone. Demikianlah anak ayam itu, setelah sampai dihadapan Raja Bone, lalu dilepaskan, ah tidak dapat lagi dibedakan karena sama bulu dan sama bunyi, begitu juga tidak diketahui yang mana betina dan mana yang jantan, karena masih sama bulu, artinya belum gugur, bulu-bulu yang ada pada lehernya. " />
        <Paragraph par="Kemudian daripada itu datang lagi perintah Raja Bone, untuk dibuatkan tali debu. Raja Sidenreng memerintahkan ketujuh anggota Adatnya mengumpulkan debu untuk diayak lalu dibasahi dengan air seperti membuat ondeh-ondeh layaknya, kemudian dipintal tetapi belum sejengkal panjangnya sudah putus lagi. " />
        <Paragraph par="Lalu dipanggil lagi La Sallomo untuk diceriterakan 14 hal tersebut, maka berkatalah La Sallomo “sungguh bodoh tuan-tuan semua, pergilah engkau suruh buat tempayan di Bilokka yang amat besar, barn dimintai kain-kain bekas kepada orang-orang Sidenreng, lalu kain itu di pintal dan di letakkan berlingkar dalam tempayan, kemudian dari itu tempayan itu dibakar dengan api, kemudian kita kirimkan kepada Raja Bone, akan nampak seperti tali debu dalam tempayan, nanti disentuh baru hancur, akan tetapi jikalau belum dipegang ia seperti tali debu”. Demikianlah akal orang Sidenreng itu sehingga tidak pernah diperangi, mereka itu hanya main politik saja, oleh karena itu orang Sidenreng tinggi politiknya. " />
        <Paragraph par="Kemudian daripada itu, Raja Bone meminta lagi tandingan lawan ada kerbau dari Raja Sidenreng, karena kerbau Raja Bone yang besar lagi berani, jarang tandingannya. Kata Addatuang, “apabila kerbau Raja Bone. itu tidak ada yang menandingi, maka kita akan diserang”. Lalu dipanggil lagi La Sallomo diceriterakan kehendak Raja Bone.Lalu kata La Sallomo." />
        <Paragraph par="“Mudah saja itu puang, kita berikan saja anak kerbau yang barn bernmur tujuh hari, anak kerbau itu telah mengenal jenis kerbau juga, meskipun anak kerbau itu belum bertanduk, lalu kita buatkan keranjang persis mulutnya, yang diselipkan taji besi pada moncongnya dan kita perhadapkan dengan kerbau Raja Bone”. " />
        <Paragraph par="Alangkah besar kerbau Raja Bone yang akan diperhadapkan dengan anak kerbau orang Sidenreng. Kata Raja Bone “Hai orang Sidenreng, di manakah tandingannya kerbauku ini”. “Ada di sini, Puang”. J awab La Sallomo. “Terlalu kecil sekali”. Kata Raja Bone " />
        <Paragraph par="“Kecil tetapi dapat mengalahkan lawannya“, jawab La Sallomo menjelaskan. Kemudian anak kerbau itu dilepaskan langsung lari menuju kerbau Raja Bone karena disangkanya adalah ibunya, tiba dekat kerbau Raja Bone langsung menusukkan mulutnya hendak menyusu, tetapi anak kerbau itu tetap membuntuti ekornya dan menyernduk masuk di antara pahanya menyelusuri tempat menyusu. " />
        <Paragraph par="Tiba-tiba kerbau Raja Bone terkena taji besi pada buah pelirnya lalu melompat lari kesakitan yang dikejar terns oleh anak kerbau itu. Maka heranlah Raja Bone dan para pengiringnya melihat, bahwa kerbaunya lari dikejar oleh kerbau yang kecil. Kata yang empunya ceritra, satu ' ketika Raja Bone akan mengadakan pameran kekayaan padi, sebab kata Raja Bone “Orang Sidenreng luas sawahnya” " />
        <Paragraph par="Maka diadakan pertandingan besarnya lumbung padi. Sebenarnya orang Sidenreng mengambil tempat pada bahagian barat Amparita yang bernama Gunung Lowa yang amat bundar bentuknya lalu gunung itu diletakkan padi berderet-deret dari bawah sampai kepuncaknya. Orangorang yang masih ada di sebelah timur Turnngengpette sudah nampak membujur gunung itu, seda,ngkan orang Bone tidak seberapa besar lumbungnya dan dicobanya menyusun lima puluh ribu ikat masih rendah sekali. " />
        <Paragraph par="Oleh karena itu Raja Bone memutuskan bahwa kita kalah atas kekayaan padi orang Sidenreng, karena menurnt laporan orang kepercayaan Raja, bahwa lumbung padi orang Sidenreng sudah n,ampak jelas menjulang di bahagian timur Turnngeng Pette dan menganggap bahwa selain daripada yang nampak menjulang seperti gunung, tentu banyak lagi yang lainnya dan itu barn satu saja lumbung kita sudah di kalahkan. Padahal pengaturan deretan padi yang diatur di gunung itu tidak sampai sepuluh ribu ikat naik keatas. Karena satu-satu ikat saja di atur naik sampai di puncaknya. Kalau bukan karena kelicikan orang Sidenreng, mungkin mereka akan menjadi budak dari orang Bone." />

        {/* <h1 className="pt-12 font-semibold">Apa pesan moral cerita rakyat Putri Tandampalik?</h1> */}
      </div>
    </div>
  )
}

export default Cerita