import React from "react";
import Title from "../../../../../components/Title";
import Image from "../../../../../components/Image";
import Paragraph from "../../../../../components/Paragraph";

function Cerita() {
  return (
    <div className="flex flex-col  p-4 items-center bg-cyan-50 gap-3 text-neutral-900">
      <div className="flex flex-col  text-justify p-2 sm:px-16 md:px-28 lg:px-32 sm:py-10 bg-champagne_pink">
        <div className="flex flex-col items-center">
          <Title text="ASAL USUL ORANG BAJO " />
          <h1 className="font-semibold text-center">Serta Hubungannya dengan Penamaan Pulau-Pulau Sembilan Di Kabupaten Sinjai/Sul-Sel.</h1>
          <Image src="/images/bajo.jpg" alt="Anak Suku Bajo" />
        </div>
        {/* Paragraf mulai */}
        <Paragraph par="Kata yang empunya ceritra pada zaman dahulu kala di daerah Sulawesi Selatan belum ada orang Bajo/Torijene (artinya orang yang berdiam diair). Konon Kabarnya orang Bajo itu berasal dari Johor/Malaysia. Pada suatu ketika putri Raja Bajo pergi bercengkerama bersuka ria naik perahu bersama dayang-dayangnya ketengah laut. Malang tak dapat ditolak sudah ditentukan oleh takdirnya, tiba-tiba Jatang angin kencang diiringi ombak besar kemudian menghanyutkan perahunya tidak tentu arah tujuannya. Mereka berteriak minta tolong tapi suaranya hilang ditelan suara gemuruh ombak yang menggulung besarnya. Berhari-hari lamanya mereka hanyut terkatung-katung mengikuti jalannya arus. Akhirnya perahu mereka terdampar ketepi pantai di muara sebuah sungai yang kemudian dikenal namanya ialah sungai Cerekang di daerah Luwu/Sulawesi Selatan. " />
        <Paragraph par="Raja orang Bajo di Johor setelah menjelang petang menunggu putrinya belum juga pulang, iapun merasa khawatir kalau-kalau putrinya belum juga pulang, iapun merasa khawatir kalau-kalau putrinya kena musibah. Beliau menyuruh pengawalnya memeriksa kepantai. Di tepi pantai dari beberapa nelayan mendapat keterangan bahwa kemungkinan besar tuan putri kena musibah sebab angin kencang dan ombak besar bertiup siang tadi. “Kami orang-orang nelayan mengurungkan maksud kami turun kelaut karena takut akan kena bahaya”. Setelah pengawal mendengar keterangan para nelayan ini, iapun segera pulang dan langsung melaporkan hal ini kepada rajanya. " />
        <Paragraph par="Raja Bajo sangat kaget mendengar berita ini dan seketika itu juga memerintahkan kepada semua orang Baja pergi mencari putrinya serta kutukan tidak boleh ada naik kedarat/pulang ke kampung apabila putri raja tidak dibawa pulang.  Orang-orang Baja dengan memakai perahu mereka terus terpencar mengarungi lautan. Dalam pelayaran itu orang-orang Baja yang sudah tua dan tak sanggup ikut meneruskan perjalanannya terpaksa singgah tapi karena takut kena kutukan rajanya, mereka tidak naik ke darat melainkan hanya membuat Rumah panggung di atas air di tepi pantai atau tetap pada perahunya yang berlabuh di tepi pantai. Tempat-tempat yang mereka lalui antara lain pesisir Sumatra, Kalimantan, Pilipina dan akhirnya terus ke Sulawesi dan tiba di teluk Bone. Orang-orang Bajo singgah di tepi pantai di teluk ini untuk beristirahat sementara, disamping itu akan mencari keterangan kalau-kalau ada yang melihat putri raja yang dicarinya. Tempat persinggahan orang-orang Baja ini kemudian dinamai BajoE (Kabupaten Bone). " />
        <Paragraph par="Setelah berapa lama mereka tinggal di BajoE akhirnya mereka mendapat keterangan bahwa putri raja yang mereka cari sekarang berada di Luwu membuat perkampungan di muara sungai Cerekang. Orang Baja di Bone ini kemudian meneruskan pelayarannya lagi menuju ke Luwu di muara sungai Cerekang. Setelah sampai disana benarlah didapati putri raja bersama dayang-dayangnya hidup dengan tenteram. Beberapa puluh tahun kemudian tersebutlah Raja Sawerigading akan berlayar ke Cina (Nama salah satu tempat di Kabupaten Bone) untuk pergi mengawini saudara sepupunya yang bernama We Cudai Daeng Risompa. Suatu kesulitan sebab perahu untuk Sawerigading ke Cina tidak ada. Sepakatlah orang-orang di Luw,u akan menebang kayu welenrengnge yang tumbuh di tepi sungai Cerekang untuk dibuatkan Sawerigading perahu. Konon kabarnya kayu welenrengnge ini adalah pohon yang terbesar diseluruh dunia pada wak tu itu. Di atas pohon kayu welenrengnge ini pada saat itu bersarang berjenis-jenis burung yang ada di Sulawesi. Setelah kayu welengrenge ini ditebang, terjadilah banjir telur burung yang pecah selama tiga bulan. Setelah itu disusul pula banjir atau air bah yang sangat besar sehingga orang-orang Bajo yang berkampung di muara Sungai cerekang hanyut akhirnya terdampar disuatu tempat yang kemudian dinamai Malili yang artinya mali = hanyut. Disinilah orang-orang Bajo yang hanyut itu tadi membuat perkampungan baru. Beberapa puluh tahun lamanya mereka berdiam di tempat ini, aman dan tenteram tak ada suatu gangguan. Maka pada suatu hari tersebutlah Putri Raja Bajo yang bernama Tuan putri Papu pergi bercengkerama dan bersuka ria naik perahu ke tengah laut. Malang datang menimpa pada saat itu tiba:tiba datang angin kencang diiringi gelombang yang besar, sehingga perahu putri Papu dan pengiringnya hanyut dibawa ombak. " />
        <Paragraph par="Pada waktu sore tibalah laporan kepada raja bahwa tuan putri bersama pengiringnya kena musibah sewaktu ia bermain-main naik perahu di tengah lautan bersama para pengiringnya. Raja Bajo di Malili memerintahkan kepada rakyatnya untuk pergi mencari putrinya hidup atau mati harus dibawa pulang. Raja juga mengeluarkan sumpah bahwa mereka akan kena kutukan apabila mereka naik kedarat tanpa memba! Y.a Tuan putri. Semua orang Bajo yang ada di Malili berangkat dan membagi dirinya atas dua kelompok. Satu kelqmpok menuju Sulawesi Tenggara, dan satu menuju ke selatan melayari Teluk Bone. Kelompok yang menuju keselatan ini terpaksa sebahagian singgah karena sakit di pulau-pulau yang bersebaran di Teluk Bone, Pulau-pulau ini sekarang bernama pulau sembilan terrnasuk Kabupaten Sinjai. Setiap pulau ini mempunyai nama tersendiri i;ebagai berikut : Sekarang namanya Pulau Liang-Hang dahulu pulau Tandotulai yang artinya ikan Katombong karena di pulau ini banyak ikan Katombong. " />
        <Paragraph par="Sekarang Pulau Kambuno dahulu Pulau Same artinya perkampungan karena dipulau inilah pertama ada perkampungan. Sekarang Pulau Katindoang dahulu Pulau Kako artinya pulau hantu karena sering dijumpai ada hantu. Sekarang Pulau Kodingngareng dahulu dinamakan Pulau Lingga yang artinya Pulau persinggahan. Sekarang Pulau Batang Lampe dahulu Batang Lambere yang artinya Pulau Panjang. Sekarang Pulau Kanalo satu dan Kanalo dua dahulu disebut Pulau Tadinang I dan Tadinang II yang artinya Pulau Pekuburan, karena disinilah dikuburkan orang-orang Bajo yang mati. " />
        <Paragraph par="Setelah orang-orang Bajo berkampung di pulau-pulau ini, pada suatu hari datanglah kawanan bajak .laut yang mengambil tempat persembunyian disalah satu pulau yang belum dihuni oleh orang Bajo. Pulau ini kemudian diberi nama BurungloE sesuai nama Kepala bajak laut yaitu BalunruE. Orang-orang Bajo disamping ad,a yang singgah di pulau-pulau yang disebut di atas, masih ada pula yang melanjutkan pelayarannya dan tiba di Selat Maka_ssar. Disini mereka menjumpai perahu yang ditumpangi .putri Papu, tetapi perahu itu sudah kosong tak ada isinya seorangpun. Mereka mengira bahwa Putri Papu telah meninggal dan dikuburkan di pulau yang ada di dekat tempat mereka menemukan perahu itu. Pulau itu mereka dekati dan akhirnya mereka·naik memeriksa kalau kalau mayat tuan putri ada tergolek. Semua tempat sudah dijelajahi tapi mayat tuan putri tidak dijumpai. Mereka pikir janganjangan mayat tuan putri dikubur dalam tanah, maka mereka menggali lagi tanah mencari rnayat yang diperkirakan ada te.rkubur. " />
        <Paragraph par="Mayat tidak didapat sehingga mereka pulang keperahunya lagi. Tempat atau Pulau ini kemudian diberi nama Tanakeke yang artinya tanah digali. Mereka melanjutkan pelayarannya dengan sedikit gembira karena perahu tuan putri sudah didapat. Tentu tuan putri ada disekitar tempat ini. Akhirnya mereka bertemu dengan beberapa orang nelayan. Dari nelayan inilah mereka mendapat keterangan bahwa putri yahg mereka cari sekarang ada di istana Raja Goa dan sudah dijadikan 'permaisuri. ·" />
        <Paragraph par="Orang-orang Bajo menuju ke Goa, setelah tiba mereka menghadap raja sekedar untuk menemui tuan putri. Akhirnya mereka bertemu dengan tuan putri yang sekarang sudah menjadi permaisuri pada kerajaan Goa. Sampai sekarang ini ada dalam nyanyian Makassar yang berbunyi : “Teako callai Bajoa rimabollong bukkulengna, niappa Bajo nania Somba ri Goa” Artinya : Jangan dicela dihina orang Bajo karena kulitnya hitam sebab nanti ada Somba karena orang Bajo. Demikianlah kissah orang Bajo dan Pulau-pulau Sembilan yang ada di Kabupaten Sinjai." />

        {/* <h1 className="pt-12 font-semibold">Apa pesan moral cerita rakyat Putri Tandampalik?</h1> */}

      </div>
    </div>
  );
}

export default Cerita;
