import React from 'react'
import Title from "../../../../../components/Title";
import Image from "../../../../../components/Image";
import Paragraph from "../../../../../components/Paragraph";

function Cerita() {
  return (
    <div className="flex flex-col  p-4 items-center bg-cyan-50 gap-3 text-neutral-900">
      <div className="flex flex-col  text-justify p-2 sm:px-16 md:px-28 lg:px-32 sm:py-10 bg-champagne_pink">
        <div className="flex flex-col items-center">
          <Title text="TERJADINYA LIMA SUNGAI BESAR DI SUL-SEL" />
          <h1 className="font-semibold text-center">(Sungai Walannae, S. Cenrana, S. Tangka. S. Apareng. S. Jenneberang)</h1>
          <Image src="/images/sungai.jpg" alt="Sungai" />
        </div>
        {/* Paragraf mulai */}
        <Paragraph par="Kata yang punya cerita, pada zaman dahulu di daerah Sulawesi Selatan belum ada sungai. Pada waktu itu daerah ini hanya dihuni oleh sebuah keluarga yang terdiri atas 7 orang: Bapak, lbu dan lima orang anaknya. Mereka berdiam di puncak gunung Bawakaraeng (sekarang termasuk Kabupaten Bantaeng). Pencaharian mereka hanyalah mencari buah-buahan di hutan, sambil berburu binatang. Pada waktu itu bercocok tanam, mereka belum ketahui begitu pula mata pencaharian lainnya. Setiap hari bapak bekerja keras untuk menghidupi keluarganya. Kelima orang anaknya namun sudah besar, tetapi tidak 5eonmgpun yang suka meinbantu ayahnya bekerja. Setiap hari pekerjaan. anak-anak ini hanyalah bermain Kata yang punya cerita, pada zaman dahulu di daerah Sulawesi Selatan belum ada sungai. Pada waktu itu daerah ini hanya dihuni oleh sebuah keluarga yang terdiri atas 7 orang: Bapak, lbu dan lima orang anaknya. Mereka berdiam di puncak gunung Bawakaraeng (sekarang termasuk Kabupaten Bantaeng). Pencaharian mereka hanyalah mencari buah-buahan di hutan, sambil berburu binatang. Pada waktu itu bercocok tanam, mereka belum ketahui begitu pula mata pencaharian lainnya. Setiap hari bapak bekerja keras untuk menghidupi keluarganya. Kelima orang anaknya namun sudah besar, tetapi tidak 5eonmgpun yang suka meinbantu ayahnya bekerja. Setiap hari pekerjaan. anak-anak ini hanyalah bermain “galenggo”, semacam permainan ketangkasan yang mempergunakan tempurung kelapa sebagai alatnya. Pada suatu hari kesabaran ayahnya tidak dapat dibendung lagi. “galenggo”, semacam permainan ketangkasan yang mempergunakan tempurung kelapa sebagai alatnya. Pada suatu hari kesabaran ayahnya tidak dapat dibendung lagi. " />
        <Paragraph par="Pada waktu itu kesehatan ayahnya agak terganggu, sehingga tidak dapat pergi jauh mencari makanan untuk hari itu. Disuruhnya anaknya pergi mencari buah-buahan di. hutan yang dapat dimakan. Anaknya yang sulung begitu pula yang lainnya tidak ada yang memperhatikan suruhan ayahnya itu. Hanyalah yang bungsu patuh mendengar perintah ayahnya itu tapi apa daya sebab ia masih kecil disamping tidak kuat bekerja, juga sangat berbahaya jalan sendiri karena banyak binatang buas dalam hutan. Ayahnya sangat marah sambil mengambil pentung, ia bangkit memburu anaknya untuk dipukul. Kelima anaknya lari pontang panting karena takut kena pukulan ayahnya. Mereka berlari terpencar untuk menyelamatkan dirinya masing-masing. Ada yang lari ke barat, ada yang lari ke timur  dan ada yang lari ke utara. Yang lari ke jurusan utara ialah anaknya yang bungsu anak kesayangannya. Sesungguhnya sang ayah tidak memarahi anaknya yang bungsu, malahan ia sangat disayangi oleh kedua orang tuanya. " />
        <Paragraph par="Si Bungsu ini memang mempunyai sifat yang berbeda dengan sifat saudara-saudaranya. Ia selalu bersedia akan membantu ayahnya bekerja, hanya sayang sekali ia masih kecil sehingga selalu dilarang oleh ayahnya terutama jika akan masuk ke hutan mencari buah-buahan. Pada waktu ayahnya memburu saudara-saudaranya, si Bungsu mengira bahwa ayahnya juga marah kepadanya dan akan memukulnya. Si Bungsu lari dan berlari sedangkan ayahnya juga lari kencang memburu dari belakang. Ayah berteriak memanggilmanggil namanya sambil disuruh berhenti. Tapi si Bungsu setiap mendengar suara ayah nya sambil menoleh ia mempercepat larinya. " />
        <Paragraph par="Sesungguhnya ayahnya memburunya bukan karena akan memukulnya, melainkan untuk menahan dan akan memanggil pulang ke rumah karena ia tidak bersalah dan tidak malas pula. Si Bungsu berlari akhirnya tiba disuatu daenih yang sekarang dinamai daerah Wajo/Sengkang. Ayahnya terus memburu dari belakang. Setelah tiba di daerah Wajo ayah kehilangan jejak anak bungsunya sehingga ia berputar-putar sambil berteriak-teriak menangis memanggil anak bungsunya. Air mata ayah yang berjatuhan sangat banyaknya ini kemudian menjadi danau yang sekarang disebµt Danau Tempe. " />
        <Paragraph par="Dari danau ini kemudian ,mengalir airnya ke Teluk Bone yang kemudfun disebut Sungai Cenrana. Si Bungsu yang· lari sambil menangis air matanya kemudian mengalir menjadi sungai yang sekarang disebut Sungai Walannae bermuara di Teluk Bone, karena memang si Bungsu berlari dari utara membelok ke timur dan menceburkan diri di Teluk Bone dan menjadi ikan Lumba-Lumba. Sampai saat ini ikarr lumba-lumba kelihatannya kepayahan apabila sekali-sekali nampak kepermukaan air. " />
        <Paragraph par="Kakak si Bungsu yang berlari kejurusan barat demikian juga halnya, berlari sambil menangis sehingga ia tiba di Selat Makassar dan menceburkan diri di selat ini. Sepanjang perjalanannya itu ia mencuourkan. air matanya, kemudian inilah yang menjadi sungai yang sekarang disebut Sungai Jeneberang. Kakak Si Bungsu ada pula yang lari ke timur dan akhirnya tiba di Teluk Bone tak ada jalan lain terpaksa menceburkan diri di taluk itu dan menjadi ikan Lumba-Lumba pula. Air rnatanya yang.bercucuran selama ia berlari itulah yang menjadi sungai yang disebut Sungai Tangka (perbatasan Kabupaten Sinjai dan Kabupaten Bone sekarang ini). lbunya yang menunggu di rumah memikirkan nasib suami dap anaknya terus menerus mencucurkan air mata dan akhirnya ia tak dapat tinggal dir.umah (di puncak gunung Bawakaraeng) menyusul suami dan anak-anaknya dan tibalah ia di Teluk Bone terus menceburkan diri di teluk itu dan menjadi ikan Lumba-lumba pula. Air matanya yang bercucurap sepanjang perjalanannya itulah menjadi sungai yang disebut. sungai Apareng (Kabupaten Sinjai)." />
        <Paragraph par="Demikian konon kisahnya tentang terjadinya Lima sungai di Sulawesi Selatan Serta terjadinya Danau Tempe yang terdapat di Kabupaten Wajo sekarang ini, juga disinggung sepintas lalu tentang terjadinya ikan lumba-lumba yang selalu kepayahan kelihatannya. Benar tidaknya Wallahu A'lam'" />
        

        {/* <h1 className="pt-12 font-semibold">Apa pesan moral cerita rakyat Putri Tandampalik?</h1> */}
      </div>
    </div>
  )
}

export default Cerita