import React from 'react'
import Image from "../../../../../components/Image";
import Paragraph from "../../../../../components/Paragraph";

function Cerita() {
  return (
    <div className="flex flex-col  p-4 items-center bg-cyan-50 gap-3 text-neutral-900">
      <div className="flex flex-col  text-justify p-2 sm:px-16 md:px-28 lg:px-32 sm:py-10 bg-champagne_pink">
        <div className="flex flex-col items-center">
          {/* <Title text="Putri Tandampalik" /> */}
          <Image src="/images/sawerigading.svg" alt="sawerigading" />
          <Image src="/images/sawerigading1.png" alt="sawerigading" />
          <Image src="/images/sawerigading2.png" alt="sawerigading" />

        </div>
        {/* Paragraf mulai */}
        <Paragraph par="Alkisah, di daerah Luwu, Sulawesi Selatan, hiduplah seorang raja bernama La Togeq Langiq atau lebih dikenal dengan panggilan Batara Lattu’. Sang Raja mempunyai dua istri, yaitu satu dari golongan manusia biasa (penduduk dunia nyata) bernama We Datu Sengeng, anak La Urumpassi dan We Padauleng ditompottikka dan satu lagi berasal dari bangsa jin.  Dari perkawinan dengan We Datu Sengeng lahir sepasang anak kembar emas, yakni seorang laki-laki bernama Sawerigading, dan seorang perempuan bernama We Tenriabeng.  " />
        <Paragraph par="Mengenai masa hidup Sawerigading terdapat berbagai versi di kalangan ahli sejarah. Menurut versi Towani-Tolotang di Sidenreng, Sawerigading lahir pada tahun 564 M. Jika versi ini dihadapkan dengan beberapa versi lain, maka data ini tidak terlalu jauh perbedaanya. Untuk lebih jelasnya, berikut ini akan dikemukakan tiga versi mengenai masa hidup Sawerigading, yaitu : " />

        <ol className='pt-2'>
          <li className="list-decimal list-inside">Versi Sulawesi Tenggara, abad V; </li>
          <li className="list-decimal list-inside">Versi Gorontalo, 900 dikurangi 50 = 850; </li>
          <li className="list-decimal list-inside">Versi Kelantan - Terengganu, tahun 710.  </li>
        </ol>
        <Paragraph par="Sepertinya, versi Sulawesi Tenggara lebih dekat dengan versi yang dikemukakan oleh masyarakat Towani-Tolotang. Mereka menetapkan versi ini sebab menurut kepercayaan mereka Sawerigading sezaman dengan Nabi Muhammad, bahkan pernah bertemu. " />
        <Paragraph par="Berdasarkan ramalan Batara Guru (ayah Raja Luwu), Sawerigading dan We Tenriabeng kelak akan saling jatuh cinta dan menikah. Padahal menurut adat setempat, seseorang sangat pantang menikahi saudara kandung sendiri. Agar tidak melanggar adat tersebut, Raja Luwu pun membesarkan kedua anak kembarnya tersebut secara terpisah. Ia menyembunyikan anak perempuannya (We Tenriabeng) di atas loteng istana sejak masih bayi.  " />
        <Paragraph par="Waktu terus berjalan. Sawerigading tumbuh menjadi pemuda yang gagah dan tampan, sedangkan We Tenriabeng tumbuh menjadi gadis yang cantik jelita. Namun, sepasang anak kembar tersebut belum saling mengenal. " />
        <Paragraph par="Pada suatu hari, Sawerigading bersama sejumlah pengawal istana diutus oleh ayahnya berlayar ke Negeri Taranati (Ternate) untuk mewakili Kerajaan Luwu dalam sebuah pertemuan para pangeran. Namun sebenarnya tujuan utama Sawerigading diutus pergi jauh ke Ternate karena saudara kembarnya We Tenriabeng akan dilantik menjadi bissu dalam sebuah upacara umum, yang tentu saja tidak boleh dihadirinya karena dikhawatirkan akan bertemu dengan We Tenriabeng. " />
        <Paragraph par="Dalam perjalanan menuju ke Negeri Ternate, Sawerigading mendapat kabar dari seorang pengawalnya bahwa ia mempunyai saudara kembar yang cantik jelita. Sawerigading tersentak kaget mendengar kabar tersebut. " />
        <Paragraph par="“Apa katamu? Aku mempunyai saudara kembar perempuan?” tanya Sawerigading dengan kaget. “Benar, Pangeran! Saudaramu itu bernama Tenriabeng. Ia disembunyikan dan dipelihara di atas loteng istana sejak masih kecil,” ungkap pengawal itu. " />
        <Paragraph par="Sekembalinya dari Ternate, Sawerigading langsung mencari saudara kembarnya yang disembunyikan di atas loteng istana. Tak pelak lagi, Sawergading langsung jatuh cinta saat melihat saudara kembarnya itu dan memutuskan untuk menikahinya. Raja Luwu Batara Lattu’ yang mengetahui rahasia keluarga istana tersebut terbongkar segera memanggil putranya itu untuk menghadap. " />
        <Paragraph par="“Wahai, Putraku! Mengharap pendamping hidup untuk saling menentramkan hati bukanlah hal yang keliru. Tapi, perlu kamu ketahui bahwa menikahi saudara kandung sendiri merupakan pantangan terbesar dalam adat istiadat kita. Jika adat ini dilanggar, bencana akan menimpa negeri ini. Sebaiknya urungkanlah niatmu itu, Putraku!” bujuk Raja Luwu Batara Lattu'. " />
        <Paragraph par="Namun, bujukan Ayahandanya tersebut tidak menyurutkan niat Sawerigading untuk menikahi adiknya. Namun, akhirnya Sawerigading mengalah setelah We Tenriabeng memberitahunya bahwa di Negeri Cina (bukan Cina di Tiongkok, tapi di daerah Tanete, Kabupetan Bone, Sulawesi Selatan) mereka mempunyai saudara sepupu yang sangat mirip dengannya.  v" />
        <Paragraph par="Untuk membuktikan kebenaran kata-katanya, We Tenriabeng memberikan sehelai rambut, sebuah gelang dan cincinnya kepada Sawerigading. We Tenriabeng juga berjanji jika perkataannya tidak benar, ia berbersedia menikah dengan Sawerigading.  " />
        <Paragraph par="“Bang! Jika rambut ini tidak sama panjang dengan rambut I We Cudai, gelang dan cincin ini tidak cocok dengan pergelangan dan jarinya, aku bersedia menikah dengan Abang,” kata We Tenriabeng. " />
        <Paragraph par="Akhirnya, Sawerigading pun bersedia berangkat ke Negeri Cina, walaupun dihatinya ada rasa kecewa kepada orang tuanya karena tidak diizinkan menikahi adiknya. We Tenriabeng sendiri naik kelangit dan kawin dengan tunangannya di sana bernama Remmang ri Langi. " />
        <Paragraph par="Untuk berlayar ke Negeri Cina, Sawerigading harus menggunakan kapal besar yang terbuat dari kayu welérénngé (kayu belande) yang mampu menahan hantaman badai dan ombak besar di tengah laut.  " />
        <Paragraph par="“Wahai, Putraku! Untuk memenuhi keinginanmu memperistri I We Cudai, besok pergilah ke hulu Sungai Saqdan menebang pohon welérénngé raksasa untuk dibuat perahu!” perintah Raja Luwu Batara Lattu’. " />
        <Paragraph par="Keesokan harinya, berangkatlah Sawerigading ke tempat yang dimaksud ayahnya itu. Ketika sampai di tempat itu, ia pun segera menebang pohon raksasa tersebut. Anehnya, walaupun batang dan pangkalnya telah terpisah, pohon raksasa itu tetap tidak mau roboh. Namun, hal itu tidak membuatnya putus asa. Keesokan harinya, Sawerigading kembali menebang pohon ajaib itu, tapi hasilnya tetap sama. Kejadian aneh ini terulang hingga tiga hari berturut-turut. Sawerigading pun mulai putus asa dan hatinya sangat galau memikirkan apa gerangan penyebabnya. " />
        <Paragraph par="Mengetahui kegalauan hati abangnya, pada malam harinya We Tenriabeng secara diam-diam pergi ke hulu Sungai Saqdan. Sungguh ajaib! Hanya sekali tebasan, pohon raksasa itu pun roboh ke tanah. Dengan ilmu yang dimilikinya, We Tenriabeng segera mengubah pohon raksasa itu menjadi sebuah perahu layar yang siap untuk mengarungi samudera luas. Keesokan harinya, Sawerigading kembali ke hulu Sungai Saqdan. Betapa terkejutnya ia ketika melihat pohon welérénngé raksasa yang tak kunjung bisa dirobohkannya kini telah berubah menjadi sebuah perahu layar.  " />
        <Paragraph par="“Hai, siapa yang melakukan semua ini?” gumam Sawerigading heran. " />
        <Paragraph par="“Ah, tidak ada gunanya aku memikirkan siapa yang telah membantuku membuat perahu layar ini. Yang pasti aku harus segera pulang untuk menyiapkan perbekalan yang akan aku bawa berlayar ke Negeri Cina,” pungkasnya seraya bergegas pulang ke istana. " />
        <Paragraph par="Setelah menyiapkan sejumlah pengawal dan perbekalan yang diperlukan, berangkatlah Sawerigading bersama rombongannya menuju Negeri Cina. Dalam perjalanan, mereka menemui berbagai tantangan dan rintangan seperti hantaman badai dan ombak serta serangan para perompak. Namun, berkat izin Tuhan Yang Mahakuasa, Sawerigading bersama pasukannya berhasil melalui semua rintangan tersebut dan selamat sampai di tujuan. " />
        <Paragraph par="Setibanya di Negeri Cina, Sawerigading mendengar kabar bahwa I We Cudai telah bertunangan dengan seorang pemuda bernama Settiaponga. Namun, hal itu tidak menyurutkan niatnyaSettiaponga akhirnya dikalahkan, dalam suatu pertempuran di tangah laut dalam perjalanan menuju ke Cina.  " />
        <Paragraph par="Untuk melihat langsung kecantikan wajah I We Cudai. Untuk itu, ia pun memutuskan untuk menyamar menjadi pedagang orang oro (berkulit hitam). Untuk memenuhi penyamarannya, ia harus mengorbankan satu nyawa orang oro sebagai tumbal. Pada mulanya, orang oro yang akan dijadikan tumbal tersebut mengiba kepadanya. " /> 
        <Paragraph par="“Ampun, Tuan! Jika kulit saya dijadikan pembungkus tubuh Tuan, tentu saya meninggal.” " /> 
        <Paragraph par=" Namun akhirnya setelah Sawerigading membujuknya dengan tutur kata yang halus, orang oro itu pun bersedia memenuhi permintaannya. Setelah Sawerigading segera menuju ke istana sebagai oro Setibanya di istana, ia terkagum-kagum melihat We Cudai. " /> 
        <Image src="/images/sawerigading3.svg" alt="sawerigading"/>
        <Paragraph par="“Benar kata Ayahanda, I We Cudai dan We Tenriabeng bagai pinang dibelah dua. Perawakan mereka benar-benar serupa,” ucap Sawerigading. " /> 
        <Paragraph par="Setelah membuktikan kecantikan I We Cudai, Sawerigading segera mengirim utusan untuk melamarnya dan lamarannya pun diterima oleh keluarga istana Kerajaan Cina. Namun, sebelum pesta pernikahan dilangsungkan, I We Cudai mengirim seorang pengawal untuk mengusut siapa sebenarnya calon suaminya itu. " /> 
        <Paragraph par="Suatu hari, utusan itu mendekati perahu layar Sawerigading yang tengah bersandar di pelabuhan. Kebetulan, saat itu para pengawal Sawerigading yang berbulu lebat sedang mandi. Utusan itu ketakukan saat melihat tampang mereka yang dikiranya “orang-orang biadab” dan mengira bahwa wujud Sawerigading serupa dengan mereka. Ia pun segera kembali istana untuk menyampaikan kabar tersebut kepada I We Cudai. Mendengar kabar tersebut, I We Cudai pun berniat untuk membatalkan pernikahannya dan mengembalikan semua mahar Sawerigading. " /> 
        <Paragraph par="Sawerigading yang mendengar kabar buruk tersebut segera menghapus penyamarannya sebagai orang oro mengenaikan pakaian kebesarannya, lalu segera menghadap Raja Cina. Sesampainya di istana, ia pun menceritakan asal-usul dan maksud kedatangannya ke Cina. " /> 
        <Paragraph par="“Ampun, Baginda Raja! Perkenalkan nama Ananda Sawerigading Putra Raja Luwu Batara Lattu’ dari Sulawesi Selatan. Ananda datang menghadap membawa amanat Ayahanda, dengan harapan sudilah kiranya Baginda menerima Ananda sebagai menantu Baginda,” ungkap Sawerigading. “Hai, Anak Muda! Kamu jangan mengaku-ngaku! Apa buktinya bahwa kamu adalah putra dari saudaraku itu?” tanya Raja Cina. " /> 
        <Paragraph par="Sawerigading pun segera memperlihatkan sehelai rambut, sebuah gelang dan cincin pemberian We Tenriabeng kepada Raja Cina seraya menceritakan semua kejadian yang dialaminya hingga ia bisa sampai ke Negeri Cina. Mendengar harapan dan permohonan saudaranya melalui keponakannya itu, Raja Cina terdiam sejenak, lalu berkata:  " /> 
        <Paragraph par="“Baiklah! Sekarang aku percaya bahwa kamu adalah keponakanku. Ayahandamu dulu pernah mengirim kabar kepadaku bahwa ia mempunyai anak kembar emas. Anaknya yang perempuan wajah dan perawakaannya serupa dengan putriku.” " /> 
        <Paragraph par="Untuk lebih meyakinkan dirinya, Raja Cina segera memanggil putrinya untuk menghadap. Tak berapa lama, I We Cudai pun datang dan duduk di samping ayahandanya. Saat melihat pemuda tampan yang duduk di hadapan ayahandanya, I We Cudai tampak gugup dan hatinya tiba-tiba berdetak kencang. Rupanya, ia jatuh hati kepada pemuda itu yang tak lain adalah Sawerigading. " /> 
        <Paragraph par="“Ada apa gerangan Ayahanda memanggil Ananda?” tanya I We Cudai tertunduk malu-malu. " /> 
        <Paragraph par="“Wahai Putriku, ketahuilah! Sesungguhnya orang yang melamarmu beberapa hari yang lalu ternyata sepupumu sendiri. Namanya Sawerigading. Ayahanda bersaudara dengan ayahnya. Tapi, untuk menyakinkan kebenaran ini, cobalah kamu cocokkan panjang rambut ini dengan panjang rambutmu dan pakailah gelang dan cincin ini!” pinta Raja Cina seraya memberikan sehelai rambut, sebuah gelang dan cincin itu kepada putrinya. " /> 
        <Paragraph par="Setelah I We Cudai mengenakan gelang dan cincin tersebut, maka semakin yakinlah Raja Cina bahwa Sawerigading benar-benar keponakannya. Gelang dan cincin tersebut semuanya cocok dikenakan oleh I We Cudai. Begitu pula rambutnya sama panjangnya dengan rambut We Tenriabeng. " /> 
        <Paragraph par="“Bagaimana, Putriku! Apakah kamu bersedia menerima kembali lamaran Sawerigading untuk mempererat tali persaudaraan kita dengan keluarga Sawerigading di Sulawesi Selatan?” tanya Raja Cina. " /> 
        <Paragraph par="“Baik, Ayahanda! Jika Ayahanda merestui, Ananda bersedia menikah dengan Sawerigading. Ananda mohon maaf karena sebelumnya mengira Sawerigading bukan dari keluarga baik-baik,” jawab I We Cudai malu-malu. " /> 
        <Paragraph par="Betapa bahagianya perasaan Raja Cina mendengar jawaban putrinya itu. Demikian pula yang dirasakan Sawerigading karena lamarannya diterima. Dengan perasaan bahagia, ia segera kembali ke kapalnya untuk menyampaikan berita gembira itu kepada para pengawalnya dan memerintahkan mereka untuk mengangkat semua barang bawaan yang ada di perahu ke istana untuk keperluan pesta.   " /> 
        <Paragraph par="Tiga hari kemudian, pesta pernikahaan itu pun dilangsungkan dengan meriah. Segenap rakyat Negeri Cina turut berbahagia menyaksikan pesta pernikahan tersebut. Sawerigading dan I We Cudai dikaruniai oleh seorang anak dan diberi nama I La Galigo , I Tenridio dan Tenribalobo .Dari seorang selirnya I We Cimpau, Sawerigading memperoleh seorang anak bernama We Tenriwaru. " /> 
        <Paragraph par="Namun, bagi I We Cudai, kebahagiaan tersebut terasa belum lengkap jika belum bertemu dengan mertuanya. Suatu hari, ia pun mengajak suaminya ke Sulawesi Selatan untuk mengunjungi mertuanya. Mulanya, Sawerigading menolak ajakan istrinya, karena ia sudah berjanji tidak ingin kembali ke kampung halamannya karena kecewa kepada kedua orang tuanya yang telah menolak keinginannya menikahi saudara kembarnya. Namun, karena istrinya terus mendesaknya, akhirnya ia pun menyetujuinya. " /> 
        <Paragraph par="Keesokan harinya, berangkatlah sepasang suami istri itu bersama beberapa orang pengawal menuju Negeri Luwu. Akan tetapi, mereka tidak membawa serta putra mereka (La Galigo) karena masih bayi. Dalam perjalanan, Sawerigading bersama rombongannya kembali menemui banyak rintangan. Perahu yang mereka tumpangi hampir tenggelam di tengah laut karena dihantam badai dan gelombang besar. Berkat pertolongan Tuhan Yang Mahakuasa, mereka pun selamat sampai di Nengeri Luwu. Setiba di Luwu, Patotoe menetapkan akan menghimpun segenap keluarganya di Luwu. Dalam pertemuan keluarga besar itulah ditetapkan bahwa keturunan dewadewa yang ada di bumi harus segera kembali kelangit atau peretiwi dengan masing-masing seorang wakil. " /> 
        <Paragraph par="Setelah bertahun-tahun lamanya Sawerigading bersama istrinya tinggal di Negeri Luwu terdengarlah kabar bahwa di Tanah Jawa berkembang ajaran agama Islam. Sawerigading pun segera memerintahkan pasukannya untuk memerangi ajaran tersebut. Namun apa yang terjadi setelah pasukannya tiba di Tanah Jawa ? Rupanya, mereka bukannya memerangi penganut ajaran agama tersebut, tetapi justru berbalik memeluk agama Islam. Bahkan sebagian anggota pasukannya memutuskan untuk menetap di Tanah Jawa. Sementara anggota pasukan lainnya kembali ke Negeri Luwu untuk melaporkan kabar tersebut kepada Sawerigading dan sekaligus mengajaknya untuk memeluk agama Islam.  " /> 
        <Paragraph par="Karena kesal atas penghianatan pasukannya itu dan tidak ingin masuk agama Islam, Sawerigading bersama istrinya memutuskan untuk kembali ke Negeri Cina dan berjanji tidak ingin menginjakkan kaki lagi di Negeri Luwu. Dalam perjalanan pulang ke Negeri Cina, kapal yang mereka tumpangi karam di tengah laut, perahunya meluncur turun ke peretiwi. Di sana ternyata disambut gembira penguasa untuk menggantikan neneknya sebagai raja peretiwi. Akhirnya tibalah saatnya pintu langit ditutup sehingga penguasa yang ada di peretiwi tidak lagi leluasa pulang pergi, dengan ketentuan sewaktu-waktu kelak akan dikirim utusan untuk memperbarui darah mereka sebagai penguasa. Konon, pasangan suami istri tersebut menjadi penguasa buriq liu atau peretiwi (dunia bawah).  " /> 

        <h1 className="pt-12 text-center font-semibold">******</h1>
        <Paragraph par="Demikian kisah SAWERIGADING PUTRA RAJA LUWU BATARA LATTU’ dari daerah Luwu, Sulawesi Selatan. Kisah ini termasuk kategori legenda yang mengandung pesan-pesan moral yang dapat dijadikan pedoman dalam kehidupan sehari-hari. " /> 
        <Paragraph par="Pesan moral yang dapat dipetik dari kisah di atas adalah ganjaran yang diterima dari sifat tidak mudah putus asa. Sifat ini ditunjukkan oleh perilaku Sawerigading yang senantiasa tabah dalam menghadapi berbagai rintangan dan cobaan untuk mencapai keinginannya, yakni menikahi I We Cudai yang berada di Negeri Cina." /> 
      </div>
    </div>
  )
}

export default Cerita